In [1]:
import numpy as np

In [49]:


def apply_noise( msg, p ):
    for i in range(len(msg)):
        if p > np.random.uniform():
            msg[i] = 1 - msg[i]

def is_valid( msg ):
    
    if len(msg) != 32: return False
    
    idx = np.arange(32)
    sum_0  = np.sum( msg[np.where( idx%1  -  0 + 1 >  0 )] ) % 2
    sum_1  = np.sum( msg[np.where( idx%2  -  1 + 1 >  0 )] ) % 2
    sum_2  = np.sum( msg[np.where( idx%4  -  2 + 1 > 0 )] ) % 2
    sum_4  = np.sum( msg[np.where( idx%8  -  4 + 1 > 0 )] ) % 2
    sum_8  = np.sum( msg[np.where( idx%16 -  8 + 1 > 0 )] ) % 2
    sum_16 = np.sum( msg[np.where( idx%32 - 16 + 1 > 0 )] ) % 2
    
    print ( 's', sum_0, sum_1, sum_2, sum_4, sum_8, sum_16 )
    
    print( sum_0*0 + sum_1*1 + sum_2*2 + sum_4*4 + sum_8*8 + sum_16*16 )
    
    return sum_1 == 0 and sum_2 == 0 and sum_4 == 0 and sum_8 == 0 and sum_16 == 0

def add_parity( msg ):
    
    idx = np.arange(32)
    msg[16] = np.sum( msg[np.where( idx%32 - 16 + 1 > 0 )] ) % 2
    msg[8]  = np.sum( msg[np.where( idx%16 -  8 + 1 > 0 )] ) % 2
    msg[4]  = np.sum( msg[np.where( idx%8  -  4 + 1 > 0 )] ) % 2
    msg[2]  = np.sum( msg[np.where( idx%4  -  2 + 1 > 0 )] ) % 2
    msg[1]  = np.sum( msg[np.where( idx%2  -  1 + 1 > 0 )] ) % 2
    msg[0]  = np.sum( msg[np.where( idx%1  -  0 + 1 > 0 )] ) % 2
    

msg = np.random.choice([0,1],32)
msg[[0,1,2,4,8,16]] = 0
add_parity( msg )
print('ck1: ', is_valid(msg))
print(str(msg))
apply_noise(msg,0.01)
print(str(msg))
print('ck2: ', is_valid(msg))


s 0 0 0 0 0 0
0
ck1:  True
[1 0 0 1 1 0 1 0 1 0 1 1 0 0 0 1 1 0 1 1 0 0 0 1 1 0 1 0 0 1 1 0]
[1 0 1 1 1 0 1 0 1 0 1 1 0 0 0 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 1 0]
s 0 0 1 1 1 1
30
ck2:  False


In [40]:
idx = np.arange(32)
np.where( idx%1  -  0 + 1 > 0 )


(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]),)

In [35]:
idx%4-2+1>0 

array([False, False,  True,  True, False, False,  True,  True, False,
       False,  True,  True, False, False,  True,  True, False, False,
        True,  True, False, False,  True,  True, False, False,  True,
        True, False, False,  True,  True])