In [1]:
import numpy as np
import matplotlib.pyplot as plt


/home/marcello/anaconda3/lib/python3.9/site-packages/numpy/_core/getlimits.py:545: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)


In [110]:

n, m = 12, 12
A = np.random.random((n,m))*2-1
np.set_printoptions(precision=2,suppress=True,linewidth=120)
A

array([[ 0.31, -0.55,  0.04, -0.92, -0.79, -0.76,  0.56, -0.01, -0.94,  0.04,  0.73,  0.76],
       [-0.29, -0.33, -0.53, -0.1 , -0.12, -0.68, -0.77, -0.15,  0.17, -0.59,  0.69,  0.05],
       [ 0.93,  0.6 ,  0.41,  0.01, -0.53,  0.89, -0.74, -0.84,  0.01,  0.56, -0.4 , -0.81],
       [-0.86,  0.57,  0.02, -0.05, -0.37,  0.25, -0.44,  0.36,  0.98,  0.04,  0.43, -0.14],
       [ 0.38, -0.69, -0.68, -0.91,  0.63,  0.63,  0.25,  0.24,  0.17,  0.92, -0.31, -0.34],
       [ 0.51,  0.15,  0.39,  0.74,  0.48, -0.14,  0.64, -0.33, -0.93, -0.82, -0.36,  0.12],
       [-0.62,  0.26, -0.26,  0.54, -0.  , -0.65,  0.29,  0.18, -0.52,  0.26,  0.55, -0.61],
       [-0.87, -0.33,  0.83,  0.56,  0.69,  0.66,  0.44, -0.58,  0.9 , -0.84,  0.56,  0.98],
       [ 0.56, -0.  , -0.31,  0.92,  0.45,  0.08, -0.51, -0.64,  0.1 , -0.13, -0.73,  0.28],
       [-0.35, -0.99, -0.29,  0.66,  0.14, -0.75,  0.64,  0.15, -0.81,  0.06,  0.36,  0.02],
       [-0.01,  0.02, -0.37, -0.61, -0.75, -0.83, -0.29,  0.37,  0.77,

In [112]:
Ap = A.copy()
Q = np.eye(n)

## Householder applied recursevily to the (n-k).(n-k) submatrix
## Assumes A is **very** well behaved
for k in range(n-1):
    x = Ap[k:,k]
    e = np.zeros_like(x); e[0] = 1.
    a = - np.sign(x[0]) * np.sqrt(np.sum(x*x)) # n-k
    u = x + a * e                              # n-k
    v = u / np.sqrt(np.sum(u*u))               # n-k
    Qp = np.eye(n)                             #
    Qp[k:,k:] += - 2. * np.outer(v , v.T)      # 
    Ap = Qp@Ap                                 # should be the larf routine from lapack -> (n-k+1)**2
    Q = Qp@Q                                   # should be the larf routine from lapack -> (n-k+1)**2
Q = Q.T    
#    print(k,Ap)

R = (Q.T@A)

print(A)
print('=')
print(Q)
print('@')
print(R)
print()
print(' A-QR = ', np.max(A-Q@R))

[[ 0.31 -0.55  0.04 -0.92 -0.79 -0.76  0.56 -0.01 -0.94  0.04  0.73  0.76]
 [-0.29 -0.33 -0.53 -0.1  -0.12 -0.68 -0.77 -0.15  0.17 -0.59  0.69  0.05]
 [ 0.93  0.6   0.41  0.01 -0.53  0.89 -0.74 -0.84  0.01  0.56 -0.4  -0.81]
 [-0.86  0.57  0.02 -0.05 -0.37  0.25 -0.44  0.36  0.98  0.04  0.43 -0.14]
 [ 0.38 -0.69 -0.68 -0.91  0.63  0.63  0.25  0.24  0.17  0.92 -0.31 -0.34]
 [ 0.51  0.15  0.39  0.74  0.48 -0.14  0.64 -0.33 -0.93 -0.82 -0.36  0.12]
 [-0.62  0.26 -0.26  0.54 -0.   -0.65  0.29  0.18 -0.52  0.26  0.55 -0.61]
 [-0.87 -0.33  0.83  0.56  0.69  0.66  0.44 -0.58  0.9  -0.84  0.56  0.98]
 [ 0.56 -0.   -0.31  0.92  0.45  0.08 -0.51 -0.64  0.1  -0.13 -0.73  0.28]
 [-0.35 -0.99 -0.29  0.66  0.14 -0.75  0.64  0.15 -0.81  0.06  0.36  0.02]
 [-0.01  0.02 -0.37 -0.61 -0.75 -0.83 -0.29  0.37  0.77 -0.08  0.65  0.35]
 [ 0.97 -0.32 -0.15 -0.84 -0.94  0.36 -0.31 -0.93 -0.44 -0.03 -0.35  0.65]]
=
[[ 0.14  0.32  0.18  0.38 -0.31  0.38  0.08 -0.14 -0.12  0.28 -0.04  0.58]
 [-0.13  0.2  -0.33 -0

In [105]:
v

array([0.43, 0.91])